#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import vm from "node:vm";

const root = resolve(import.meta.dirname, "..");
const sourcePath = resolve(root, "public/topics.js");
const outputPath = resolve(root, "src/topics.ts");
const checkOnly = process.argv.includes("--check");

const source = await readFile(sourcePath, "utf8");
const sandbox = {};
vm.runInNewContext(
  `${source}\n;globalThis.__copycatTopics = TOPICS; globalThis.__copycatLangs = SUPPORTED_LANGS;`,
  sandbox,
  { filename: sourcePath },
);

const topics = sandbox.__copycatTopics;
const languages = sandbox.__copycatLangs;
const errors = [];
if (!Array.isArray(languages) || languages.length === 0) errors.push("SUPPORTED_LANGS must be a non-empty array");
if (!Array.isArray(topics) || topics.length === 0) errors.push("TOPICS must be a non-empty array");

const ids = new Set();
for (const [topicIndex, topic] of (topics || []).entries()) {
  const label = `TOPICS[${topicIndex}]`;
  if (!topic || typeof topic !== "object") {
    errors.push(`${label} must be an object`);
    continue;
  }
  if (typeof topic.id !== "string" || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(topic.id)) {
    errors.push(`${label}.id must use lowercase kebab-case`);
  } else if (ids.has(topic.id)) {
    errors.push(`${label}.id duplicates "${topic.id}"`);
  } else {
    ids.add(topic.id);
  }
  if (!Array.isArray(topic.words) || topic.words.length !== 16) {
    errors.push(`${label}.words must contain exactly 16 entries`);
  }
  for (const language of languages || []) {
    if (typeof topic.title?.[language] !== "string" || !topic.title[language].trim()) {
      errors.push(`${label}.title.${language} is required`);
    }
    const localizedWords = new Set();
    for (const [wordIndex, word] of (topic.words || []).entries()) {
      const value = word?.[language];
      if (typeof value !== "string" || !value.trim()) {
        errors.push(`${label}.words[${wordIndex}].${language} is required`);
      } else if (localizedWords.has(value.trim().toLocaleLowerCase(language))) {
        errors.push(`${label} contains a duplicate ${language} word: "${value}"`);
      } else {
        localizedWords.add(value.trim().toLocaleLowerCase(language));
      }
    }
  }
}

if (errors.length) {
  process.stderr.write(`Topic validation failed:\n- ${errors.join("\n- ")}\n`);
  process.exit(1);
}

const englishTopics = topics.map((topic) => ({
  id: topic.id,
  title: topic.title.en,
  words: topic.words.map((word) => word.en),
}));
const generated = `// Generated by scripts/sync-topics.mjs from public/topics.js. Do not edit by hand.\n` +
`// Append cards to TOPICS, then run npm run topics:sync. Existing order is a persisted game identifier.\n\n` +
`export interface BuiltinTopic {\n  id: string;\n  title: string;\n  words: string[];\n}\n\n` +
`export const BUILTIN_TOPICS_EN: BuiltinTopic[] = ${JSON.stringify(englishTopics, null, 2)};\n\n` +
`export const BUILTIN_TOPIC_COUNT = BUILTIN_TOPICS_EN.length;\n\n` +
`export function getBuiltinTopic(index: number): BuiltinTopic {\n` +
`  return BUILTIN_TOPICS_EN[index] ?? BUILTIN_TOPICS_EN[0];\n` +
`}\n`;

if (checkOnly) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== generated) {
    process.stderr.write("src/topics.ts is out of date. Run npm run topics:sync.\n");
    process.exit(1);
  }
  process.stdout.write(`Validated ${topics.length} topics × ${languages.length} languages.\n`);
} else {
  await writeFile(outputPath, generated);
  process.stdout.write(`Synced ${topics.length} topics × ${languages.length} languages to src/topics.ts.\n`);
}
