// Generated by scripts/sync-topics.mjs from public/topics.js. Do not edit by hand.
// Append cards to TOPICS, then run npm run topics:sync. Existing order is a persisted game identifier.

export interface BuiltinTopic {
  id: string;
  title: string;
  words: string[];
}

export const BUILTIN_TOPICS_EN: BuiltinTopic[] = [
  {
    "id": "animals",
    "title": "Animals",
    "words": [
      "Lion",
      "Panda",
      "Elephant",
      "Giraffe",
      "Penguin",
      "Dolphin",
      "Koala",
      "Rabbit",
      "Hippo",
      "Owl",
      "Gorilla",
      "Cat",
      "Dog",
      "Hamster",
      "Crocodile",
      "Turtle"
    ]
  },
  {
    "id": "food",
    "title": "Food",
    "words": [
      "Pizza",
      "Sushi",
      "Hamburger",
      "Ramen",
      "Curry",
      "Tacos",
      "Pasta",
      "Fried chicken",
      "Sandwich",
      "Steak",
      "Salad",
      "Ice cream",
      "Dumplings",
      "Pancakes",
      "Hot dog",
      "Fried rice"
    ]
  },
  {
    "id": "sports",
    "title": "Sports",
    "words": [
      "Soccer",
      "Baseball",
      "Basketball",
      "Tennis",
      "Table tennis",
      "Swimming",
      "Marathon",
      "Skiing",
      "Boxing",
      "Golf",
      "Volleyball",
      "Rugby",
      "Judo",
      "Gymnastics",
      "Skateboarding",
      "Surfing"
    ]
  },
  {
    "id": "jobs",
    "title": "Jobs",
    "words": [
      "Doctor",
      "Teacher",
      "Police officer",
      "Pilot",
      "Chef",
      "Programmer",
      "Firefighter",
      "Hairdresser",
      "Lawyer",
      "Farmer",
      "Singer",
      "Astronaut",
      "Carpenter",
      "Nurse",
      "Actor",
      "Driver"
    ]
  },
  {
    "id": "things-at-home",
    "title": "Things at Home",
    "words": [
      "Fridge",
      "TV",
      "Sofa",
      "Microwave",
      "Washing machine",
      "Vacuum",
      "Bed",
      "Air conditioner",
      "Mirror",
      "Bookshelf",
      "Curtains",
      "Table",
      "Hair dryer",
      "Clock",
      "House plant",
      "Lamp"
    ]
  },
  {
    "id": "fruits",
    "title": "Fruits",
    "words": [
      "Apple",
      "Banana",
      "Strawberry",
      "Grapes",
      "Orange",
      "Watermelon",
      "Melon",
      "Peach",
      "Pineapple",
      "Kiwi",
      "Cherry",
      "Lemon",
      "Mango",
      "Pear",
      "Coconut",
      "Blueberry"
    ]
  },
  {
    "id": "instruments",
    "title": "Instruments",
    "words": [
      "Piano",
      "Guitar",
      "Violin",
      "Drums",
      "Flute",
      "Trumpet",
      "Saxophone",
      "Harmonica",
      "Ukulele",
      "Cello",
      "Harp",
      "Recorder",
      "Bass",
      "Organ",
      "Accordion",
      "Xylophone"
    ]
  },
  {
    "id": "vehicles",
    "title": "Vehicles",
    "words": [
      "Train",
      "Airplane",
      "Bicycle",
      "Bus",
      "Taxi",
      "Ship",
      "Helicopter",
      "Motorcycle",
      "Tram",
      "Rocket",
      "Hot air balloon",
      "Submarine",
      "Fire truck",
      "Ambulance",
      "Truck",
      "Cable car"
    ]
  },
  {
    "id": "school",
    "title": "School",
    "words": [
      "Blackboard",
      "Desk",
      "Gym",
      "Pool",
      "Library",
      "Playground",
      "Homework",
      "Exam",
      "Backpack",
      "Pencil",
      "Eraser",
      "Notebook",
      "School bell",
      "Uniform",
      "School lunch",
      "Classroom"
    ]
  },
  {
    "id": "countries",
    "title": "Countries",
    "words": [
      "Japan",
      "USA",
      "France",
      "Italy",
      "Brazil",
      "Egypt",
      "India",
      "Australia",
      "Canada",
      "Germany",
      "Spain",
      "China",
      "Mexico",
      "Russia",
      "UK",
      "South Korea"
    ]
  }
];

export const BUILTIN_TOPIC_COUNT = BUILTIN_TOPICS_EN.length;

export function getBuiltinTopic(index: number): BuiltinTopic {
  return BUILTIN_TOPICS_EN[index] ?? BUILTIN_TOPICS_EN[0];
}
